from typing import Any, Literal

class Tensor:
    dtype: str
    shape: list[int]
    strides: list[int]
    ndim: int
    is_contiguous: bool
    empty: bool
    device: str
    is_tracked: bool

    def __init__(self, data: Any, dtype: str | None = ...) -> None: ...
    def numel(self) -> int: ...
    def item(self) -> float: ...
    def tolist(self) -> Any: ...
    def detach(self) -> Tensor: ...
    def clone(self) -> Tensor: ...
    def contiguous(self, always_copy: bool = ...) -> Tensor: ...
    def reshape(self, shape: list[int]) -> Tensor: ...
    def flatten(self) -> Tensor: ...
    def transpose(self) -> Tensor: ...
    def permute(self, axes: list[int]) -> Tensor: ...
    def squeeze(self) -> Tensor: ...
    def unsqueeze(self, axis: int) -> Tensor: ...
    def broadcast_to(self, shape: list[int]) -> Tensor: ...
    def sum(self, axis: int | None = ...) -> Tensor: ...
    def mean(self, axis: int | None = ...) -> Tensor: ...
    def max(self) -> Tensor: ...
    def min(self) -> Tensor: ...
    def exp(self) -> Tensor: ...
    def log(self) -> Tensor: ...
    def sqrt(self) -> Tensor: ...
    def abs(self) -> Tensor: ...
    def relu(self) -> Tensor: ...
    def sigmoid(self) -> Tensor: ...
    def tanh(self) -> Tensor: ...
    def pow(self, exponent: float) -> Tensor: ...
    def allclose(self, other: Tensor, tolerance: float = ...) -> bool: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int | list[int]) -> float: ...
    def __setitem__(self, index: int | list[int], value: float) -> None: ...
    def __neg__(self) -> Tensor: ...
    def __add__(self, other: Tensor | float) -> Tensor: ...
    def __radd__(self, other: float) -> Tensor: ...
    def __sub__(self, other: Tensor | float) -> Tensor: ...
    def __rsub__(self, other: float) -> Tensor: ...
    def __mul__(self, other: Tensor | float) -> Tensor: ...
    def __rmul__(self, other: float) -> Tensor: ...
    def __truediv__(self, other: Tensor | float) -> Tensor: ...
    def __rtruediv__(self, other: float) -> Tensor: ...
    def __matmul__(self, other: Tensor) -> Tensor: ...
    def __pow__(self, exponent: float) -> Tensor: ...
    def __abs__(self) -> Tensor: ...

class Trace:
    def __init__(self, dtype: str = ...) -> None: ...
    def __enter__(self) -> Trace: ...
    def __exit__(self, *args: Any) -> Literal[False]: ...

def attach(tensor: Tensor) -> Tensor: ...
def backward(output: Tensor) -> None: ...
def adjoint(tensor: Tensor) -> Tensor: ...
def stop_gradient(tensor: Tensor) -> Tensor: ...
def zeros(shape: list[int], dtype: str | None = ...) -> Tensor: ...
def ones(shape: list[int], dtype: str | None = ...) -> Tensor: ...
def full(shape: list[int], value: float, dtype: str | None = ...) -> Tensor: ...
def uninitialized(shape: list[int], dtype: str | None = ...) -> Tensor: ...
def matmul(a: Tensor, b: Tensor) -> Tensor: ...
def exp(tensor: Tensor) -> Tensor: ...
def log(tensor: Tensor) -> Tensor: ...
def sqrt(tensor: Tensor) -> Tensor: ...
def abs(tensor: Tensor) -> Tensor: ...
def relu(tensor: Tensor) -> Tensor: ...
def sigmoid(tensor: Tensor) -> Tensor: ...
def tanh(tensor: Tensor) -> Tensor: ...
